### ISSUE TITLE
ActiveMQ Connection Problem?

### ISSUE THREAD

**Issue by nmaas87** [celery/kombu#723] opened 2017-04-19 15:17 UTC
As soon as I try to connect to ActiveMQ 5.14.5, 

````
  activemq_connection = Connection("amqp://" + username + ":" + password + "@" + ip + ":5672//")
  activemq_connection.connect()
  activemq_publisher = activemq_connection.SimpleQueue("file")
````
python crashes:
````
Traceback (most recent call last):
  File "./send_activemq.py", line 317, in <module>
    mq_connect(server_ip,'user','password')
  File "./send_activemq.py", line 268, in mq_connect
    activemq_connection.connect()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 261, in connect
    return self.connection
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 802, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/connection.py", line 757, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 130, in establish_connection
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 300, in connect
    self.drain_events(timeout=self.connect_timeout)
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 464, in drain_events
    return self.blocking_read(timeout)
  File "/usr/local/lib/python2.7/dist-packages/amqp/connection.py", line 468, in blocking_read
    frame = self.transport.read_frame()
  File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 247, in read_frame
    payload = read(size)
  File "/usr/local/lib/python2.7/dist-packages/amqp/transport.py", line 385, in _read
    raise IOError('Socket closed')
IOError: Socket closed
````

AMQP tells me this:
````
 WARN | Connection attempt from non AMQP v1.0 client. AMQP,1,1,0,9
 WARN | Transport Connection to: tcp://IP:59230 failed: org.apache.activemq.transport.amqp.AmqpProtocolException: Connection from client using unsupported AMQP attempted
 WARN | Transport Connection to: tcp://IP:36818 failed: java.net.SocketException: Connection reset
````

qpid does also not work as transport.. How can I get this working?
Thanks a lot :)!

**Comment by georgepsarakis** [comment] 2017-04-28 05:09
I think ActiveMQ supports [AMQP 1.0](http://activemq.apache.org/amqp.html). I am not sure that the AMQP client is fully compliant with this protocol version. Check also the corresponding documentation [page](https://www.rabbitmq.com/protocols.html) for RabbitMQ.

**Comment by thedrow** [comment] 2017-07-25 14:27
Could this be an authentication error?

**Comment by siraajahmed** [comment] 2017-09-21 14:06
I had a similar issue.

Adding SASL Mechanism "Anonymous" when connecting worked a treat.

`client.connect(uri, {'saslMechanism':'ANONYMOUS'})...`

Got it from https://stackoverflow.com/questions/43873400/unable-to-connect-to-apache-activemq-with-node-js#answer-43913433

**Comment by thedrow** [comment] 2017-09-24 06:07
Yup, that's it. I'm going to close this issue since it's not a bug.

**Closed by thedrow** 2017-09-24 06:07 UTC
Labels: Component: AMQP Broker

**Comment by mattbennett** [comment] 2018-12-14 13:57
This issue is closed as not a bug, but appears to be a duplicate of #5001, which is still open

**Comment by thedrow** [comment] 2018-12-16 09:06
We still plan to add support for ActiveMQ at some point.

**Comment by mattbennett** [comment] 2018-12-16 09:19
The confusing thing about this issue is that it suggests kombu _can_ connect to ActiveMQ if the “authentication error” is addressed.
