### ISSUE TITLE
Celery continuously warning "No hostname was supplied. Reverting to default 'None'"

### ISSUE THREAD

**Issue by WhyNotHugo** [celery/kombu#1357] opened 2021-07-21 19:16 UTC
After updating from:

```diff
 name = "celery"
-version = "5.0.5"
+version = "5.1.2"
 name = "kombu"
-version = "5.0.2"
+version = "5.1.0"
```

Kombu continuously emits this warning:

    No hostname was supplied. Reverting to default 'None'

It seems to happen every time I queue a celery task (i.e.: `my_task.delay() from a celery task.

```
  File "celery", line 8, in <module>
    sys.exit(main())
  File "celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
  File "celery/bin/worker.py", line 346, in worker
    worker.start()
  File "celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "kombu/asynchronous/hub.py", line 361, in create_loop
    cb(*cbargs)
  File "celery/concurrency/asynpool.py", line 482, in _event_process_exit
    self.maintain_pool()
  File "billiard/pool.py", line 1351, in maintain_pool
    self._maintain_pool()
  File "billiard/pool.py", line 1343, in _maintain_pool
    self._repopulate_pool(joined)
  File "billiard/pool.py", line 1328, in _repopulate_pool
    self._create_worker_process(self._avail_index())
  File "celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
  File "billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
  File "billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
  File "billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
  File "billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
  File "billiard/process.py", line 327, in _bootstrap
    self.run()
  File "billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "celery/app/trace.py", line 646, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "idf/sync/tasks.py", line 86, in generate_missing_archives
    tasks.post_process_order.delay(archive.order_id)
  File "celery/app/task.py", line 422, in delay
    return self.apply_async(args, kwargs)
  File "celery/app/task.py", line 572, in apply_async
    return app.send_task(
  File "celery/app/base.py", line 763, in send_task
    with self.producer_or_acquire(producer) as P:
  File "celery/utils/objects.py", line 84, in __enter__
    context = self._context = self.fallback(
  File "kombu/resource.py", line 81, in acquire
    R = self.prepare(R)
  File "kombu/pools.py", line 60, in prepare
    p = p()
  File "kombu/utils/functional.py", line 186, in __call__
    return self.evaluate()
  File "kombu/utils/functional.py", line 189, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "kombu/pools.py", line 40, in create_producer
    conn = self._acquire_connection()
  File "kombu/pools.py", line 37, in _acquire_connection
    return self.connections.acquire(block=True)
  File "kombu/resource.py", line 81, in acquire
    R = self.prepare(R)
  File "kombu/connection.py", line 1017, in prepare
    resource = resource()
  File "kombu/utils/functional.py", line 186, in __call__
    return self.evaluate()
  File "kombu/utils/functional.py", line 189, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "kombu/connection.py", line 989, in new
    return self.connection.clone()
  File "kombu/connection.py", line 618, in clone
    return self.__class__(**dict(self._info(resolve=False), **kwargs))
  File "kombu/connection.py", line 631, in _info
    logger.warning(
  File "__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "__init__.py", line 1589, in _log
    self.handle(record)
  File "__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "__init__.py", line 952, in handle
    self.emit(record)
```

Variables

D | {port: None}
-- | --
resolve | False
self | <Connection: sqs://localhost// at 0x7f784f4823a0>
transport_cls | 'sqs'

Can this have negative side effects, or should I worry about it? What exactly is wrong here?

**Comment by DragosChirila** [comment] 2021-08-06 00:21
We have the same problem after moving to celery==5.1.2 and kombu==5.1.0

**Comment by thedrow** [comment] 2021-08-09 08:49
Do you have a way we can reproduce the issue?

**Comment by DragosChirila** [comment] 2021-08-09 22:36
@thedrow Yes, I do. The setup and all the details are the same as in this one https://github.com/celery/celery/issues/6895

Please let me know if you need further details. Thank you.

**Comment by WhyNotHugo** [comment] 2021-08-13 11:44
Do you have any feedback on whetheer  this have negative side effects, or should I worry about it?

I understand fixing it may take time, but I want to know if this can have any impact I should be concerned about, of if I can safely ignore this for now.

**Comment by thedrow** [comment] 2021-08-16 14:14
There are probably monitoring repercussions if you use flower as the hostname won't be reported.

**Comment by thedrow** [comment] 2021-08-16 14:27
Are we sure this warning comes from Celery?
Because I just grepped the code and it's not there.

**Comment by WhyNotHugo** [comment] 2021-08-16 14:50
It's here:

https://github.com/celery/kombu/blob/c0f2b847f05aa960f0c0d25ce5fcdd0078ec45b8/kombu/connection.py#L629-L633

Here's my full stacktrace (hope this helps somehow) for this:

```
  File "celery", line 8, in <module>
    sys.exit(main())
  File "celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
  File "click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
  File "celery/bin/worker.py", line 346, in worker
    worker.start()
  File "celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "celery/worker/loops.py", line 81, in asynloop
    next(loop)
  File "kombu/asynchronous/hub.py", line 300, in create_loop
    poll_timeout = fire_timers(propagate=propagate) if scheduled else 1
  File "kombu/asynchronous/hub.py", line 142, in fire_timers
    entry()
  File "kombu/asynchronous/timer.py", line 65, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "kombu/asynchronous/timer.py", line 127, in _reschedules
    return fun(*args, **kwargs)
  File "billiard/pool.py", line 1351, in maintain_pool
    self._maintain_pool()
  File "billiard/pool.py", line 1343, in _maintain_pool
    self._repopulate_pool(joined)
  File "billiard/pool.py", line 1328, in _repopulate_pool
    self._create_worker_process(self._avail_index())
  File "celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
  File "billiard/pool.py", line 1158, in _create_worker_process
    w.start()
  File "billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
  File "billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
  File "billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
  File "billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
  File "billiard/process.py", line 327, in _bootstrap
    self.run()
  File "billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
  File "billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "celery/app/trace.py", line 646, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
  File "celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "celery/app/autoretry.py", line 34, in run
    return task._orig_run(*args, **kwargs)
  File "idf/core/tasks/afip.py", line 136, in validate_receipt
    generate_pdf_receipt.delay(receipt.pk)
  File "celery/app/task.py", line 422, in delay
    return self.apply_async(args, kwargs)
  File "celery/app/task.py", line 572, in apply_async
    return app.send_task(
  File "celery/app/base.py", line 763, in send_task
    with self.producer_or_acquire(producer) as P:
  File "celery/utils/objects.py", line 84, in __enter__
    context = self._context = self.fallback(
  File "kombu/resource.py", line 81, in acquire
    R = self.prepare(R)
  File "kombu/pools.py", line 60, in prepare
    p = p()
  File "kombu/utils/functional.py", line 186, in __call__
    return self.evaluate()
  File "kombu/utils/functional.py", line 189, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "kombu/pools.py", line 40, in create_producer
    conn = self._acquire_connection()
  File "kombu/pools.py", line 37, in _acquire_connection
    return self.connections.acquire(block=True)
  File "kombu/resource.py", line 81, in acquire
    R = self.prepare(R)
  File "kombu/connection.py", line 1017, in prepare
    resource = resource()
  File "kombu/utils/functional.py", line 186, in __call__
    return self.evaluate()
  File "kombu/utils/functional.py", line 189, in evaluate
    return self._fun(*self._args, **self._kwargs)
  File "kombu/connection.py", line 989, in new
    return self.connection.clone()
  File "kombu/connection.py", line 618, in clone
    return self.__class__(**dict(self._info(resolve=False), **kwargs))
  File "kombu/connection.py", line 631, in _info
    logger.warning(
  File "__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "__init__.py", line 1589, in _log
    self.handle(record)
  File "__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "__init__.py", line 952, in handle
    self.emit(record)
```

**Comment by thedrow** [comment] 2021-08-16 15:04
Do tasks get executed?

**Comment by WhyNotHugo** [comment] 2021-08-16 15:34
I believe they do. This triggers a task that generates some files, and I don't see any of those missing.

**Comment by thedrow** [comment] 2021-08-17 09:19
This is definitely a bug but I don't think it has an impact.

**Comment by thedrow** [comment] 2021-08-17 09:20
@galCohen88 Can you take a loot at this please?

**Comment by cbporch** [comment] 2021-11-05 13:34
I'm also experiencing this issue. It's quite a noisy warning considering there are no obvious negative effects, at least not when using SQS.

**Comment by hcNick** [comment] 2022-01-11 09:18
@thedrow @galCohen88 Is there any update here? This warning is swamping Sentry. Thanks

**Comment by hcNick** [comment] 2022-01-11 09:22
@Krogsager is it possible to add an exception for this warning for SQS?

**Comment by WhyNotHugo** [comment] 2022-01-11 09:44
You can ignore this warning with:

```python
import warnings

warnings.filterwarnings("ignore", "No hostname was supplied")
```

I had to add this after the issue quickly ate my Sentry quota for a month.

**Closed** 2022-02-02 13:23 UTC
Labels: Component: Amazon SQS Broker, Issue Type: Bug Report

**Comment by WhyNotHugo** [comment] 2022-02-03 14:36
Thanks for the well detailed description in 2f3b153acce0ab826ed23caffd9a293978cfc168, I appreciate understanding what was causing this.

**Comment by sergey-jr** [comment] 2023-01-25 13:31
i have same isue on 5.2.0

**Comment by JPereira-FJB** [comment] 2023-05-11 15:56
The issue remains on 5.2.7. Any updates on the correct to tackle this without just ignoring the warning?

**Comment by Drvmnekta** [comment] 2024-03-28 09:15
I have same issue on 5.3.6 It becomes an error on linux server during pipeline in gitlab. The problem line is result.revoke. Other celery tests pass normally
